### ISSUE TITLE
PV/PVC  accessMode  loss RWOP

### ISSUE THREAD

**Issue by wuchubin** [tengqm/kab#2]
The ReadWriteOncePod access mode is only supported for [CSI](https://kubernetes.io/docs/concepts/storage/volumes/#csi) volumes and Kubernetes version 1.22+，GA in 1.29, but I can not see in enum of the swagger.json

**Comment by tengqm** [comment]
It is not in the original swagger. Need to check the reason.

**Comment by tengqm** [comment]
fixed in 28d9e961
